### ISSUE TITLE
Access URL is not mentioned

### ISSUE THREAD

**Issue by Laxman-SM** [frntn/docker-datacenter-helper#1]
HI,

can you please update the Access URL , that is missing. i found access URL in vagrant environment is:

https://192.168.0.5/

**Comment by frntn** [comment]
Thanks.
The dashboard URL is now echoed to stdout.

Demo available here : https://asciinema.org/a/cdzjbkx6hgm5lfbda48j1oi0q?autoplay=1&speed=2
